spring:
  application:
    name: coretime

  profiles:
    default: dev

    # Common JPA/Hibernate Settings ---
    jpa:
      properties:
        hibernate:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoreNamingStrategy

      hibernate:
        ddl-auto: none